# User configuration for CyTube bot

# Connection settings
rooms:
  - room: fatpizza
    server: https://cytu.be
    username: ${BOT_USERNAME}
    password: ${BOT_PASSWORD}
  - room: RIFFTRAX_MST3K
    server: https://cytu.be
    username: ${BOT_USERNAME}
    password: ${BOT_PASSWORD}

# Module overrides
modules:
  # Core modules are always enabled
  core-database:
    enabled: true
  
  core-api:
    enabled: true  # Re-enabled for modular architecture
    port: 3002
  
  core-connection:
    enabled: true  # Re-enabled for modular architecture
  
  # Feature modules can be toggled
  command-handler:
    enabled: true  # Re-enabled for modular architecture
  
  economy:
    enabled: false  # Disable until converted
  
  greeting:
    enabled: false  # Disable until converted

# Logging
logging:
  level: info